// Biznes yo'nalishlari va ularga tegishli faoliyat turlari.

import type { BusinessDirection } from "./types";

export const QUEUE_DIRECTIONS = [
  "Transport va logistika",
  "Xizmat ko'rsatish",
  "Maishiy xizmatlar",
  "Qurilish",
  "Tibbiy xizmatlar",
  "Ko'chmas mulk",
  "Axborot texnologiyalari",
  "Konsalting va professional",
  "Madaniyat, sport, ko'ngilochar",
  "Turizm va mehmonxona",
  "Reklama va marketing",
  "Poligrafiya va nashriyot",
  "Moliyaviy faoliyat",
  "Import-eksport",
] as const;

export function queueUiLabels(direction: string) {
  const medical = direction === "Tibbiy xizmatlar";
  return {
    medical,
    provider: medical ? "Shifokor" : "Xizmat ko‘rsatuvchi",
    providers: medical ? "Shifokorlar" : "Xizmat ko‘rsatuvchilar",
    customer: medical ? "Bemor" : "Mijoz",
  };
}

export const BUSINESS_DIRECTIONS: readonly BusinessDirection[] = [
  {
    name: "Savdo",
    icon: "🛒",
    activities: [
      "Oziq-ovqat do'koni",
      "Kiyim-kechak",
      "Poyabzal",
      "Elektronika",
      "Maishiy texnika",
      "Telefon va aksessuar",
      "Qurilish mollari",
      "Mebel do'koni",
      "Uy jihozlari",
      "Dorixona",
      "Optika",
      "Parfyumeriya va kosmetika",
      "Zargarlik",
      "Bolalar mollari",
      "Kanselyariya",
      "Gullar do'koni",
      "Sport mollari",
      "Kitob do'koni",
      "Avtoehtiyot qismlar",
      "Bozor rastasi",
    ],
  },
  {
    name: "Transport va logistika",
    icon: "🚕",
    activities: [
      "Taxi",
      "Yo'lovchi tashish",
      "Yuk tashish",
      "Yetkazib berish",
      "Kuryer xizmati",
      "Evakuator",
      "Avto ijara",
      "Ombor xizmati",
      "Konteyner tashish",
      "Refrijerator tashish",
    ],
  },
  {
    name: "Xizmat ko'rsatish",
    icon: "🧰",
    activities: [
      "Kunlik ishchi",
      "Uy tozalash",
      "Santexnik",
      "Elektrik",
      "Konditsioner ta'miri",
      "Muzlatgich ta'miri",
      "Kir yuvish mashinasi ta'miri",
      "Kompyuter ta'miri",
      "Telefon ta'miri",
      "Payvandchi",
      "Bo'yoqchi",
      "Mebel yig'uvchi",
      "Eshik-deraza ustasi",
      "Uy ko'chirish",
      "Bog'bon",
    ],
  },
  {
    name: "Maishiy xizmatlar",
    icon: "💇",
    activities: [
      "Sartaroshxona",
      "Go'zallik saloni",
      "Manikur-pedikur",
      "Kosmetolog",
      "Massaj",
      "Qosh-kiprik",
      "Makiyaj ustasi",
      "Tikuvchilik",
      "Poyabzal ta'miri",
      "Kimyoviy tozalash",
      "Solaryum",
      "Hammom va sauna",
    ],
  },
  {
    name: "Umumiy ovqatlanish",
    icon: "🍽️",
    activities: [
      "Kafe",
      "Restoran",
      "Fast-food",
      "Milliy taomlar",
      "Choyxona",
      "Pitseriya",
      "Sushi bar",
      "Kofeynya",
      "Nonvoyxona",
      "Qandolatxona",
      "Oshxona",
      "Yetkazib beruvchi oshxona",
    ],
  },
  {
    name: "Qurilish",
    icon: "🏗️",
    activities: [
      "Quruvchi brigada",
      "Ta'mirlash (remont)",
      "Montaj ishlari",
      "Loyihalash",
      "Tom yopish",
      "Beton quyish",
      "Gips-karton",
      "Kafel-plitka",
      "Elektromontaj",
      "Santexmontaj",
      "Fasad ishlari",
      "Landshaft dizayni",
      "Quduq qazish",
    ],
  },
  {
    name: "Tibbiy xizmatlar",
    icon: "🩺",
    activities: [
      "Klinika",
      "Stomatologiya",
      "Laboratoriya",
      "Shifokor konsultatsiyasi",
      "Hamshira xizmati",
      "Ginekologiya",
      "Pediatriya",
      "UZI diagnostika",
      "Fizioterapiya",
      "Oftalmologiya",
      "Massaj kabineti",
      "Veterinariya",
    ],
  },
  {
    name: "Ta'lim faoliyati",
    icon: "📚",
    activities: [
      "O'quv markazi",
      "Repetitor",
      "Til kurslari",
      "IT kurslari",
      "Avtomaktab",
      "Musiqa maktabi",
      "Sport maktabi",
      "Rassomlik",
      "Xoreografiya",
      "Bog'cha",
      "Onlayn kurslar",
      "Imtihonga tayyorlash",
    ],
  },
  {
    name: "Ko'chmas mulk",
    icon: "🏢",
    activities: [
      "Rieltor",
      "Kvartira sotish",
      "Uy sotish",
      "Yer uchastkasi",
      "Ijaraga berish",
      "Tijorat ko'chmas mulki",
      "Bino boshqaruvi",
      "Baholash xizmati",
    ],
  },
  {
    name: "Qishloq xo'jaligi",
    icon: "🌾",
    activities: [
      "Dehqonchilik",
      "Chorvachilik",
      "Parrandachilik",
      "Asalarichilik",
      "Bog'dorchilik",
      "Issiqxona",
      "Baliqchilik",
      "Urug' va ko'chat",
      "Em-xashak",
      "Sut mahsulotlari",
    ],
  },
  {
    name: "Axborot texnologiyalari",
    icon: "💻",
    activities: [
      "Dasturlash",
      "Veb-sayt yaratish",
      "Mobil ilova",
      "Grafik dizayn",
      "SMM",
      "1C dasturlash",
      "Kompyuter tarmoqlari",
      "Kiberxavfsizlik",
      "Video montaj",
      "IT xizmat",
    ],
  },
  {
    name: "Konsalting va professional",
    icon: "⚖️",
    activities: [
      "Advokat",
      "Yuridik maslahat",
      "Buxgalteriya",
      "Soliq maslahati",
      "Audit",
      "Notarius",
      "Tarjimon",
      "Biznes-reja",
      "HR xizmati",
      "Litsenziya olish",
    ],
  },
  {
    name: "Madaniyat, sport, ko'ngilochar",
    icon: "🏟️",
    activities: [
      "Sport zali",
      "Fitnes klub",
      "Suzish havzasi",
      "Bilyard",
      "Bouling",
      "Kvest xona",
      "Foto-video",
      "To'yxona",
      "Tadbir tashkil etish",
      "DJ xizmati",
      "Tamada",
      "Sharlar bilan bezash",
    ],
  },
  {
    name: "Turizm va mehmonxona",
    icon: "🏨",
    activities: [
      "Mehmonxona",
      "Hostel",
      "Kvartira sutkalik",
      "Dam olish maskani",
      "Sanatoriy",
      "Turagentlik",
      "Ekskursiya",
      "Aviachipta",
      "Viza xizmati",
    ],
  },
  {
    name: "Ishlab chiqarish",
    icon: "🏭",
    activities: [
      "Oziq-ovqat ishlab chiqarish",
      "Mebel",
      "Tikuv sexi",
      "Metall konstruksiyalar",
      "Plastik buyumlar",
      "Qurilish materiallari",
      "Ichimliklar",
      "Qadoqlash",
      "Oyna-deraza",
    ],
  },
  {
    name: "Hunarmandchilik",
    icon: "🧵",
    activities: [
      "Yog'och buyumlar",
      "Charm buyumlar",
      "Kulolchilik",
      "Kashtachilik",
      "Zardo'zlik",
      "Gilamdo'zlik",
      "Milliy liboslar",
      "Suvenir",
      "Qo'lda yasalgan buyumlar",
    ],
  },
  {
    name: "Reklama va marketing",
    icon: "📣",
    activities: [
      "SMM",
      "Targetolog",
      "Kontekst reklama",
      "Banner va dizayn",
      "Kontent yaratish",
      "Blogger reklama",
      "Reklama agentligi",
    ],
  },
  {
    name: "Poligrafiya va nashriyot",
    icon: "🖨️",
    activities: [
      "Chop etish",
      "Vizitka va buklet",
      "Banner bosish",
      "Muhr-tamg'a",
      "Stiker",
      "Futbolkaga bosish",
      "Lazer o'yish",
      "Kitob nashri",
      "Kalendar",
    ],
  },
  {
    name: "Moliyaviy faoliyat",
    icon: "💳",
    activities: [
      "Sug'urta",
      "Mikroqarz",
      "Pul o'tkazmalari",
      "Valyuta ayirboshlash",
      "Lizing",
      "Kredit maslahati",
      "Investitsiya maslahati",
    ],
  },
  {
    name: "Import-eksport",
    icon: "🚢",
    activities: [
      "Import",
      "Eksport",
      "Bojxona vositachiligi",
      "Xalqaro logistika",
      "Sertifikatlash",
      "Tashqi savdo maslahati",
    ],
  },
] as const;

export function directionActivities(direction: string, current = ""): string[] {
  const found = BUSINESS_DIRECTIONS.find((item) => item.name === direction);
  const activities = found ? [...found.activities] : [];
  if (current && !activities.includes(current)) activities.unshift(current);
  return activities;
}
