// Kabinet menyulari: onlayn, tizim, admin va yo'nalish menyulari.

import { QUEUE_DIRECTIONS } from "./directions";
import type { Menu } from "./types";

export const ONLINE_MENUS: Menu[] = [
  {
    icon: "🏪",
    label: "Profil / Mening sahifam",
    caption: "Mijozlar ko‘radigan ma’lumotlar",
    view: "profile",
  },
  {
    icon: "💎",
    label: "Obunalarim",
    caption: "Bepul, Plus va Pro tariflari",
    view: "subscriptions",
    payload: "business_subscriptions",
  },
  {
    icon: "💳",
    label: "To‘lovlarim",
    caption: "Yuborilgan to‘lovlar va tarix",
    view: "payments",
    payload: "subscription_payments",
  },
  {
    icon: "🛍️",
    label: "Mahsulot va xizmatlar",
    caption: "Guruhlar va katalog yozuvlari",
    view: "items",
    payload: ["item_groups", "items"],
  },
  {
    icon: "🍽️",
    label: "Stollar va xonalar",
    caption: "Zal rejasini joylashtirish",
    view: "dining-places",
    payload: "dining_places",
    directions: ["Umumiy ovqatlanish"],
  },
  {
    icon: "👨‍🍳",
    label: "Oshpaz buyurtmalari",
    caption: "Tayyorlanayotgan ichki zakazlar",
    view: "dining-kitchen",
    payload: "dining_orders",
    directions: ["Umumiy ovqatlanish"],
  },
  {
    icon: "📥",
    label: "Kursga yozilishlar",
    caption: "Yangi arizalarni guruhga qabul qilish",
    view: "education-enrollments",
    payload: "education_enrollments",
    directions: ["Ta'lim faoliyati"],
  },
  {
    icon: "🧑‍💼",
    label: "Xizmat ko‘rsatuvchilar",
    caption: "Xizmat ko‘rsatuvchi kartasi, xizmat va ish jadvali",
    view: "medical-providers",
    payload: "medical_doctors",
    directions: QUEUE_DIRECTIONS,
  },
  {
    icon: "🏥",
    label: "Navbat boshqaruvi",
    caption: "Onlayn va oflayn yagona navbat",
    view: "medical-queue",
    payload: "medical_queue",
    directions: QUEUE_DIRECTIONS,
  },
  {
    icon: "📢",
    label: "E’lonlarim",
    caption: "Biznes nomidan joylangan e’lonlar",
    view: "listings",
    payload: "listings",
  },
  {
    icon: "📦",
    label: "Buyurtmalar",
    caption: "Mahsulot buyurtmalari",
    view: "orders",
    payload: "orders",
  },
  {
    icon: "🧰",
    label: "Xizmat buyurtmalari",
    caption: "Xizmat va navbatlar",
    view: "service-orders",
    payload: "orders",
  },
  {
    icon: "💬",
    label: "Suhbatlar",
    caption: "Mijozlar bilan xabarlar",
    view: "messages",
    payload: "messages",
  },
  {
    icon: "⭐",
    label: "Mijoz fikrlari",
    caption: "Baholar va javoblar",
    view: "reviews",
    payload: "business_reviews",
  },
  {
    icon: "📣",
    label: "Reklamalarim",
    caption: "Banner va ko‘rsatish tarixi",
    view: "advertisements",
    payload: "advertisements",
  },
  {
    icon: "🎞️",
    label: "Istoriya arxivi",
    caption: "Faol va arxivdagi istoriyalar",
    view: "stories",
    payload: "stories",
  },
  {
    icon: "🔔",
    label: "Bildirishnomalarim",
    caption: "Biznes xabarlari",
    view: "notifications",
    payload: "notifications",
  },
  {
    icon: "👥",
    label: "Obunachilar",
    caption: "Biznesni kuzatayotgan profillar",
    view: "followers",
    payload: "followers",
  },
  {
    icon: "🔗",
    label: "Biznes obunalari",
    caption: "Biznes nomidan kuzatilayotgan profillar",
    view: "following",
    payload: "following",
  },
];

export const SYSTEM_MENUS: Menu[] = [
  {
    icon: "🧾",
    label: "Kassa",
    caption: "Savdo daftari va kassa harakatlari",
    view: "sales",
    payload: ["sales", "cash_transactions", "cash_register_transactions"],
  },
  {
    icon: "💸",
    label: "Xarajatlar",
    caption: "Kunlik xarajatlar hisobi",
    view: "expenses",
    payload: "expenses",
  },
  {
    icon: "📒",
    label: "Qarz daftari",
    caption: "Mijozlar qarzi va tranzaksiyalar",
    view: "debtors",
    payload: ["debtors", "qarz_transactions"],
  },
  {
    icon: "📦",
    label: "Ombor",
    caption: "Qoldiq va kirim-chiqim",
    view: "warehouse",
    payload: ["warehouse_items", "warehouse_tx"],
  },
  {
    icon: "📊",
    label: "Statistika",
    caption: "Tushum, xarajat va faoliyat",
    view: "statistics",
    excludedDirections: ["Ta'lim faoliyati", "Ta’lim faoliyati"],
  },
  {
    icon: "📄",
    label: "Hisobotlar",
    caption: "Ko‘chirilgan davriy ko‘rsatkichlar",
    view: "reports",
  },
  {
    icon: "🤖",
    label: "AI yordamchi",
    caption: "Savdo, ombor, qarz bo'yicha savol bering",
    view: "ai-assistant",
  },
  {
    icon: "⚙️",
    label: "Sozlamalar",
    caption: "Login, til va bildirishnomalar",
    view: "settings",
  },
];

export const ADMIN_MENUS: Menu[] = [
  {
    icon: "👨‍💼",
    label: "Xodimlar",
    caption: "Xodim va kirish ma’lumotlari",
    view: "staff",
    payload: ["staff", "business_staff", "employees"],
  },
  {
    icon: "🪪",
    label: "Mening hujjatlarim",
    caption: "Rahbar va STIR ma’lumotlari",
    view: "my-documents",
  },
  {
    icon: "📄",
    label: "Hujjatlar",
    caption: "Kiruvchi, chiquvchi, ichki, kontragentlar",
    view: "documents",
  },
];

export const DIRECTION_MENUS: Menu[] = [
  {
    icon: "👨‍🏫",
    label: "Ta’lim guruhlari",
    caption: "Guruh va dars ma’lumotlari",
    view: "education-groups",
    payload: "education_groups",
    directions: ["Ta'lim faoliyati", "Ta’lim faoliyati"],
  },
  {
    icon: "🎓",
    label: "O‘quvchilar",
    caption: "O‘quvchi va to‘lov holatlari",
    view: "education-students",
    payload: "education_students",
    directions: ["Ta'lim faoliyati", "Ta’lim faoliyati"],
  },
  {
    icon: "🗓️",
    label: "Dars jadvali",
    caption: "Haftalik guruh va o‘qituvchilar jadvali",
    view: "education-schedule",
    directions: ["Ta'lim faoliyati", "Ta’lim faoliyati"],
  },
  {
    icon: "✅",
    label: "Davomat",
    caption: "O‘quvchilarning darsga qatnashuvi",
    view: "education-attendance",
    directions: ["Ta'lim faoliyati", "Ta’lim faoliyati"],
  },
  {
    icon: "💳",
    label: "To‘lov nazorati",
    caption: "Muddati kelgan va yaqin to‘lovlar",
    view: "education-payments",
    directions: ["Ta'lim faoliyati", "Ta’lim faoliyati"],
  },
  {
    icon: "🧑‍🏫",
    label: "O‘qituvchilar",
    caption: "O‘qituvchi ma’lumotlari",
    view: "education-teachers",
    payload: "education_teachers",
    directions: ["Ta'lim faoliyati", "Ta’lim faoliyati"],
  },
  {
    icon: "💰",
    label: "O‘qituvchi maoshi",
    caption: "Hisoblangan va to‘langan maoshlar",
    view: "education-payroll",
    directions: ["Ta'lim faoliyati", "Ta’lim faoliyati"],
  },
  {
    icon: "📊",
    label: "Ta'lim statistikasi",
    caption: "Davomat, to'lovlar, maosh va natija",
    view: "education-statistics",
    directions: ["Ta'lim faoliyati", "Ta’lim faoliyati"],
  },
];
