"""Katalog: 20 faoliyat yo'nalishi (kelishilgan tartibda) va ularning faoliyat turlari."""

CATALOG = [
    {"name": "Savdo", "ic": "🛒",
     "t": ["Oziq-ovqat do'koni", "Kiyim-kechak", "Elektronika", "Qurilish mollari", "Dorixona", "Bozor rastasi"]},
    {"name": "Transport va logistika", "ic": "🚕",
     "t": ["Taxi", "Yuk tashish", "Yetkazib berish", "Yo'lovchi tashish", "Evakuator"]},
    {"name": "Xizmat ko'rsatish", "ic": "🧰",
     "t": ["Kunlik ishchi", "Uy tozalash", "Texnika ta'miri", "Santexnik", "Elektrik"]},
    {"name": "Maishiy xizmatlar", "ic": "💇",
     "t": ["Sartaroshxona", "Go'zallik saloni", "Tikuvchilik", "Poyabzal ta'miri", "Kimyoviy tozalash"]},
    {"name": "Umumiy ovqatlanish", "ic": "🍽️",
     "t": ["Kafe", "Restoran", "Fast-food", "Oshxona", "Qandolatxona"]},
    {"name": "Qurilish", "ic": "🏗️",
     "t": ["Quruvchi brigada", "Ta'mirlash", "Montaj ishlari", "Loyihalash"]},
    {"name": "Tibbiy xizmatlar", "ic": "🩺",
     "t": ["Klinika", "Stomatologiya", "Laboratoriya", "Shifokor konsultatsiyasi", "Hamshira xizmati"]},
    {"name": "Ta'lim faoliyati", "ic": "📚",
     "t": ["O'quv markazi", "Repetitor", "Til kurslari", "IT kurslari", "Bog'cha"]},
    {"name": "Ko'chmas mulk", "ic": "🏢",
     "t": ["Rieltor", "Ijaraga berish", "Bino boshqaruvi"]},
    {"name": "Qishloq xo'jaligi", "ic": "🌾",
     "t": ["Dehqonchilik", "Chorvachilik", "Issiqxona", "Baliqchilik"]},
    {"name": "Axborot texnologiyalari", "ic": "💻",
     "t": ["Dasturlash", "Veb-sayt", "Mobil ilova", "IT xizmat"]},
    {"name": "Konsalting va professional", "ic": "⚖️",
     "t": ["Advokat", "Buxgalteriya", "Audit", "Notarius", "Tarjimon"]},
    {"name": "Madaniyat, sport, ko'ngilochar", "ic": "🏟️",
     "t": ["Sport zali", "Foto-video", "Tadbir tashkil etish", "To'yxona"]},
    {"name": "Turizm va mehmonxona", "ic": "🏨",
     "t": ["Mehmonxona", "Hostel", "Turagentlik"]},
    {"name": "Ishlab chiqarish", "ic": "🏭",
     "t": ["Oziq-ovqat ishlab chiqarish", "Mebel", "Tikuv sexi", "Plastik buyumlar"]},
    {"name": "Hunarmandchilik", "ic": "🧵",
     "t": ["Yog'och buyumlar", "Charm buyumlar", "Suvenir", "Zardo'zlik"]},
    {"name": "Reklama va marketing", "ic": "📣",
     "t": ["SMM", "Banner / dizayn", "Reklama agentligi"]},
    {"name": "Poligrafiya va nashriyot", "ic": "🖨️",
     "t": ["Chop etish", "Vizitka / buklet", "Muhr-tamg'a", "Stiker"]},
    {"name": "Moliyaviy faoliyat", "ic": "💳",
     "t": ["Sug'urta", "Lizing", "Investitsiya maslahati"]},
    {"name": "Import-eksport", "ic": "🚢",
     "t": ["Import", "Eksport", "Bojxona vositachiligi"]},
]

# E'lon toifalari
LISTING_CATS = [
    {"key": "uy", "name": "Uy-joy", "ic": "🏠"},
    {"key": "ish", "name": "Ish o'rinlari", "ic": "💼"},
    {"key": "moshina", "name": "Moshinalar", "ic": "🚙"},
    {"key": "hayvon", "name": "Hayvonlar", "ic": "🐾"},
    {"key": "texnika", "name": "Texnika", "ic": "📱"},
    {"key": "boshqa", "name": "Boshqalar", "ic": "📦"},
]
