"""Backend uchun mustaqil O'zbekiston tuman/shahar nomlari katalogi."""

DISTRICT_NAMES = (
    'Bektemir', 'Chilonzor', 'Mirobod', "Mirzo Ulug'bek", 'Olmazor', 'Sergeli', 'Uchtepa', 'Shayxontohur',
    'Yakkasaroy', 'Yashnobod', 'Yunusobod', 'Angren', 'Bekobod', "Bo'ka", "Bo'stonliq (Gazalkent)", 'Chinoz',
    'Chirchiq', 'Nurafshon', 'Ohangaron', "Oqqo'rg'on", 'Parkent', 'Piskent', 'Qibray', "Yangiyo'l",
    'Zangiota', 'Andijon shahri', 'Asaka', 'Baliqchi', "Bo'z", 'Buloqboshi', 'Izboskan', 'Jalaquduq',
    'Marhamat', "Oltinko'l", 'Paxtaobod', "Qo'rg'ontepa", 'Shahrixon', "Ulug'nor", "Xo'jaobod", "Farg'ona shahri",
    "Marg'ilon", "Qo'qon", 'Quvasoy', 'Beshariq', "Bog'dod", 'Buvayda', "Dang'ara", 'Furqat',
    "Qo'shtepa", 'Rishton', "So'x", 'Toshloq', "Uchko'prik", 'Yozyovon', 'Namangan shahri', 'Chortoq',
    'Chust', 'Kosonsoy', 'Mingbuloq', 'Norin', 'Pop', "To'raqo'rg'on", "Uchqo'rg'on", 'Uychi',
    "Yangiqo'rg'on", 'Samarqand shahri', "Kattaqo'rg'on", "Bulung'ur", 'Ishtixon', 'Jomboy', "Qo'shrabot", 'Narpay (Oqtosh)',
    'Nurobod', 'Oqdaryo', "Pastdarg'om", 'Paxtachi', 'Payariq', 'Toyloq', 'Urgut', 'Buxoro shahri',
    'Kogon', "G'ijduvon", 'Jondor', "Qorako'l", 'Qorovulbozor', 'Olot', 'Peshku', 'Romitan',
    'Shofirkon', 'Vobkent', 'Qarshi', 'Shahrisabz', 'Kitob', "G'uzor", 'Qamashi', 'Koson',
    'Mirishkor (Pomuq)', 'Muborak', 'Nishon', 'Chiroqchi', "Yakkabog'", 'Dehqonobod', 'Kasbi', 'Termiz',
    'Denov', 'Boysun', "Sho'rchi", 'Angor', "Jarqo'rg'on", 'Qiziriq', "Qumqo'rg'on", 'Muzrabot',
    'Oltinsoy', 'Sariosiyo', 'Sherobod', 'Uzun', 'Jizzax shahri', 'Arnasoy', 'Baxmal', "Do'stlik",
    'Forish', "G'allaorol", "Mirzacho'l", 'Paxtakor', 'Yangiobod', 'Zomin', 'Zarbdor', 'Sharof Rashidov',
    'Guliston', 'Yangiyer', 'Shirin', 'Boyovut', 'Sayxunobod', 'Sardoba', 'Mirzaobod', 'Oqoltin',
    'Xovos', 'Sirdaryo', 'Navoiy shahri', 'Zarafshon', 'Karmana', 'Konimex', 'Qiziltepa', 'Navbahor',
    'Nurota', 'Tomdi', 'Uchquduq', 'Xatirchi', 'Urganch', 'Xiva', "Bog'ot", 'Gurlan',
    'Xonqa', 'Hazorasp', "Qo'shko'pir", 'Shovot', 'Yangiariq', 'Yangibozor', 'Nukus', 'Beruniy',
    'Chimboy', "Ellikqal'a (Bo'ston)", 'Kegeyli', "Mo'ynoq", "Qonliko'l", "Qo'ng'irot", "Qorao'zak", 'Shumanay',
    "Taxtako'pir", "To'rtko'l", "Xo'jayli", "Amudaryo (Mang'it)",
)
