export interface UzbekistanRegion {
  name: string;
  districts: readonly string[];
}

// Canonical names extracted from static/regions.js in v1656.
export const UZBEKISTAN_REGIONS: readonly UzbekistanRegion[] = [
  {
    name: "Toshkent shahri",
    districts: [
      "Bektemir",
      "Chilonzor",
      "Mirobod",
      "Mirzo Ulug'bek",
      "Olmazor",
      "Sergeli",
      "Uchtepa",
      "Shayxontohur",
      "Yakkasaroy",
      "Yashnobod",
      "Yunusobod",
    ],
  },
  {
    name: "Toshkent viloyati",
    districts: [
      "Angren",
      "Bekobod",
      "Bo'ka",
      "Bo'stonliq (Gazalkent)",
      "Chinoz",
      "Chirchiq",
      "Nurafshon",
      "Ohangaron",
      "Oqqo'rg'on",
      "Parkent",
      "Piskent",
      "Qibray",
      "Yangiyo'l",
      "Zangiota",
    ],
  },
  {
    name: "Andijon viloyati",
    districts: [
      "Andijon shahri",
      "Asaka",
      "Baliqchi",
      "Bo'z",
      "Buloqboshi",
      "Izboskan",
      "Jalaquduq",
      "Marhamat",
      "Oltinko'l",
      "Paxtaobod",
      "Qo'rg'ontepa",
      "Shahrixon",
      "Ulug'nor",
      "Xo'jaobod",
    ],
  },
  {
    name: "Farg'ona viloyati",
    districts: [
      "Farg'ona shahri",
      "Marg'ilon",
      "Qo'qon",
      "Quvasoy",
      "Beshariq",
      "Bog'dod",
      "Buvayda",
      "Dang'ara",
      "Furqat",
      "Qo'shtepa",
      "Rishton",
      "So'x",
      "Toshloq",
      "Uchko'prik",
      "Yozyovon",
    ],
  },
  {
    name: "Namangan viloyati",
    districts: [
      "Namangan shahri",
      "Chortoq",
      "Chust",
      "Kosonsoy",
      "Mingbuloq",
      "Norin",
      "Pop",
      "To'raqo'rg'on",
      "Uchqo'rg'on",
      "Uychi",
      "Yangiqo'rg'on",
    ],
  },
  {
    name: "Samarqand viloyati",
    districts: [
      "Samarqand shahri",
      "Kattaqo'rg'on",
      "Bulung'ur",
      "Ishtixon",
      "Jomboy",
      "Qo'shrabot",
      "Narpay (Oqtosh)",
      "Nurobod",
      "Oqdaryo",
      "Pastdarg'om",
      "Paxtachi",
      "Payariq",
      "Toyloq",
      "Urgut",
    ],
  },
  {
    name: "Buxoro viloyati",
    districts: [
      "Buxoro shahri",
      "Kogon",
      "G'ijduvon",
      "Jondor",
      "Qorako'l",
      "Qorovulbozor",
      "Olot",
      "Peshku",
      "Romitan",
      "Shofirkon",
      "Vobkent",
    ],
  },
  {
    name: "Qashqadaryo viloyati",
    districts: [
      "Qarshi",
      "Shahrisabz",
      "Kitob",
      "G'uzor",
      "Qamashi",
      "Koson",
      "Mirishkor (Pomuq)",
      "Muborak",
      "Nishon",
      "Chiroqchi",
      "Yakkabog'",
      "Dehqonobod",
      "Kasbi",
    ],
  },
  {
    name: "Surxondaryo viloyati",
    districts: [
      "Termiz",
      "Denov",
      "Boysun",
      "Sho'rchi",
      "Angor",
      "Jarqo'rg'on",
      "Qiziriq",
      "Qumqo'rg'on",
      "Muzrabot",
      "Oltinsoy",
      "Sariosiyo",
      "Sherobod",
      "Uzun",
    ],
  },
  {
    name: "Jizzax viloyati",
    districts: [
      "Jizzax shahri",
      "Arnasoy",
      "Baxmal",
      "Do'stlik",
      "Forish",
      "G'allaorol",
      "Mirzacho'l",
      "Paxtakor",
      "Yangiobod",
      "Zomin",
      "Zarbdor",
      "Sharof Rashidov",
    ],
  },
  {
    name: "Sirdaryo viloyati",
    districts: [
      "Guliston",
      "Yangiyer",
      "Shirin",
      "Boyovut",
      "Sayxunobod",
      "Sardoba",
      "Mirzaobod",
      "Oqoltin",
      "Xovos",
      "Sirdaryo",
    ],
  },
  {
    name: "Navoiy viloyati",
    districts: [
      "Navoiy shahri",
      "Zarafshon",
      "Karmana",
      "Konimex",
      "Qiziltepa",
      "Navbahor",
      "Nurota",
      "Tomdi",
      "Uchquduq",
      "Xatirchi",
    ],
  },
  {
    name: "Xorazm viloyati",
    districts: [
      "Urganch",
      "Xiva",
      "Bog'ot",
      "Gurlan",
      "Xonqa",
      "Hazorasp",
      "Qo'shko'pir",
      "Shovot",
      "Yangiariq",
      "Yangibozor",
    ],
  },
  {
    name: "Qoraqalpog'iston Respublikasi",
    districts: [
      "Nukus",
      "Beruniy",
      "Chimboy",
      "Ellikqal'a (Bo'ston)",
      "Kegeyli",
      "Mo'ynoq",
      "Qonliko'l",
      "Qo'ng'irot",
      "Qorao'zak",
      "Shumanay",
      "Taxtako'pir",
      "To'rtko'l",
      "Xo'jayli",
      "Amudaryo (Mang'it)",
    ],
  },
];
