export interface CatalogDirection {
  readonly id: string;
  readonly name: string;
  readonly icon: string;
  readonly color: string;
  readonly activityTypes: readonly string[];
}

export const CATALOG_DIRECTIONS: readonly CatalogDirection[] = [
  {
    id: "trade",
    name: "Savdo",
    icon: "🛒",
    color: "#EF4444",
    activityTypes: [
      "Oziq-ovqat do‘koni",
      "Kiyim-kechak",
      "Poyabzal",
      "Elektronika",
      "Maishiy texnika",
      "Telefon va aksessuar",
      "Qurilish mollari",
      "Mebel do‘koni",
      "Uy jihozlari",
      "Dorixona",
      "Optika",
      "Parfyumeriya va kosmetika",
      "Zargarlik",
      "Bolalar mollari",
      "Kanselyariya",
      "Gullar do‘koni",
      "Sport mollari",
      "Kitob do‘koni",
      "Avtoehtiyot qismlar",
      "Bozor rastasi",
    ],
  },
  {
    id: "transport-logistics",
    name: "Transport va logistika",
    icon: "🚕",
    color: "#2563EB",
    activityTypes: [
      "Taxi",
      "Yo‘lovchi tashish",
      "Yuk tashish",
      "Yetkazib berish",
      "Kuryer xizmati",
      "Evakuator",
      "Avto ijara",
      "Ombor xizmati",
      "Konteyner tashish",
      "Refrijerator tashish",
    ],
  },
  {
    id: "services",
    name: "Xizmat ko‘rsatish",
    icon: "🧰",
    color: "#0E8C84",
    activityTypes: [
      "Kunlik ishchi",
      "Uy tozalash",
      "Santexnik",
      "Elektrik",
      "Konditsioner ta’miri",
      "Muzlatgich ta’miri",
      "Kir yuvish mashinasi ta’miri",
      "Kompyuter ta’miri",
      "Telefon ta’miri",
      "Payvandchi",
      "Bo‘yoqchi",
      "Mebel yig‘uvchi",
      "Eshik-deraza ustasi",
      "Uy ko‘chirish",
      "Bog‘bon",
    ],
  },
  {
    id: "household-services",
    name: "Maishiy xizmatlar",
    icon: "💇",
    color: "#EC4899",
    activityTypes: [
      "Sartaroshxona",
      "Go‘zallik saloni",
      "Manikur-pedikur",
      "Kosmetolog",
      "Massaj",
      "Qosh-kiprik",
      "Makiyaj ustasi",
      "Tikuvchilik",
      "Poyabzal ta’miri",
      "Kimyoviy tozalash",
      "Solaryum",
      "Hammom va sauna",
    ],
  },
  {
    id: "food-service",
    name: "Umumiy ovqatlanish",
    icon: "🍽️",
    color: "#F97316",
    activityTypes: [
      "Kafe",
      "Restoran",
      "Fast-food",
      "Milliy taomlar",
      "Choyxona",
      "Pitseriya",
      "Sushi bar",
      "Kofeynya",
      "Nonvoyxona",
      "Qandolatxona",
      "Oshxona",
      "Yetkazib beruvchi oshxona",
    ],
  },
  {
    id: "construction",
    name: "Qurilish",
    icon: "🏗️",
    color: "#F0A21B",
    activityTypes: [
      "Quruvchi brigada",
      "Ta’mirlash (remont)",
      "Montaj ishlari",
      "Loyihalash",
      "Tom yopish",
      "Beton quyish",
      "Gips-karton",
      "Kafel-plitka",
      "Elektromontaj",
      "Santexmontaj",
      "Fasad ishlari",
      "Landshaft dizayni",
      "Quduq qazish",
    ],
  },
  {
    id: "medical-services",
    name: "Tibbiy xizmatlar",
    icon: "🩺",
    color: "#16A34A",
    activityTypes: [
      "Klinika",
      "Stomatologiya",
      "Laboratoriya",
      "Shifokor konsultatsiyasi",
      "Hamshira xizmati",
      "Ginekologiya",
      "Pediatriya",
      "UZI diagnostika",
      "Fizioterapiya",
      "Oftalmologiya",
      "Massaj kabineti",
      "Veterinariya",
    ],
  },
  {
    id: "education",
    name: "Ta’lim faoliyati",
    icon: "📚",
    color: "#6366F1",
    activityTypes: [
      "O‘quv markazi",
      "Repetitor",
      "Til kurslari",
      "IT kurslari",
      "Avtomaktab",
      "Musiqa maktabi",
      "Sport maktabi",
      "Rassomlik",
      "Xoreografiya",
      "Bog‘cha",
      "Onlayn kurslar",
      "Imtihonga tayyorlash",
    ],
  },
  {
    id: "real-estate",
    name: "Ko‘chmas mulk",
    icon: "🏢",
    color: "#0EA5E9",
    activityTypes: [
      "Rieltor",
      "Kvartira sotish",
      "Uy sotish",
      "Yer uchastkasi",
      "Ijaraga berish",
      "Tijorat ko‘chmas mulki",
      "Bino boshqaruvi",
      "Baholash xizmati",
    ],
  },
  {
    id: "agriculture",
    name: "Qishloq xo‘jaligi",
    icon: "🌾",
    color: "#65A30D",
    activityTypes: [
      "Dehqonchilik",
      "Chorvachilik",
      "Parrandachilik",
      "Asalarichilik",
      "Bog‘dorchilik",
      "Issiqxona",
      "Baliqchilik",
      "Urug‘ va ko‘chat",
      "Em-xashak",
      "Sut mahsulotlari",
    ],
  },
  {
    id: "information-technology",
    name: "Axborot texnologiyalari",
    icon: "💻",
    color: "#8B5CF6",
    activityTypes: [
      "Dasturlash",
      "Veb-sayt yaratish",
      "Mobil ilova",
      "Grafik dizayn",
      "SMM",
      "1C dasturlash",
      "Kompyuter tarmoqlari",
      "Kiberxavfsizlik",
      "Video montaj",
      "IT xizmat",
    ],
  },
  {
    id: "consulting",
    name: "Konsalting va professional",
    icon: "⚖️",
    color: "#475569",
    activityTypes: [
      "Advokat",
      "Yuridik maslahat",
      "Buxgalteriya",
      "Soliq maslahati",
      "Audit",
      "Notarius",
      "Tarjimon",
      "Biznes-reja",
      "HR xizmati",
      "Litsenziya olish",
    ],
  },
  {
    id: "culture-sports-entertainment",
    name: "Madaniyat, sport, ko‘ngilochar",
    icon: "🏟️",
    color: "#DC2626",
    activityTypes: [
      "Sport zali",
      "Fitnes klub",
      "Suzish havzasi",
      "Bilyard",
      "Bouling",
      "Kvest xona",
      "Foto-video",
      "To‘yxona",
      "Tadbir tashkil etish",
      "DJ xizmati",
      "Tamada",
      "Sharlar bilan bezash",
    ],
  },
  {
    id: "tourism-hospitality",
    name: "Turizm va mehmonxona",
    icon: "🏨",
    color: "#0891B2",
    activityTypes: [
      "Mehmonxona",
      "Hostel",
      "Kvartira sutkalik",
      "Dam olish maskani",
      "Sanatoriy",
      "Turagentlik",
      "Ekskursiya",
      "Aviachipta",
      "Viza xizmati",
    ],
  },
  {
    id: "manufacturing",
    name: "Ishlab chiqarish",
    icon: "🏭",
    color: "#78716C",
    activityTypes: [
      "Oziq-ovqat ishlab chiqarish",
      "Mebel",
      "Tikuv sexi",
      "Metall konstruksiyalar",
      "Plastik buyumlar",
      "Qurilish materiallari",
      "Ichimliklar",
      "Qadoqlash",
      "Oyna-deraza",
    ],
  },
  {
    id: "crafts",
    name: "Hunarmandchilik",
    icon: "🧵",
    color: "#B45309",
    activityTypes: [
      "Yog‘och buyumlar",
      "Charm buyumlar",
      "Kulolchilik",
      "Kashtachilik",
      "Zardo‘zlik",
      "Gilamdo‘zlik",
      "Milliy liboslar",
      "Suvenir",
      "Qo‘lda yasalgan buyumlar",
    ],
  },
  {
    id: "advertising-marketing",
    name: "Reklama va marketing",
    icon: "📣",
    color: "#DB2777",
    activityTypes: [
      "SMM",
      "Targetolog",
      "Kontekst reklama",
      "Banner va dizayn",
      "Kontent yaratish",
      "Blogger reklama",
      "Reklama agentligi",
    ],
  },
  {
    id: "printing-publishing",
    name: "Poligrafiya va nashriyot",
    icon: "🖨️",
    color: "#4B5563",
    activityTypes: [
      "Chop etish",
      "Vizitka va buklet",
      "Banner bosish",
      "Muhr-tamg‘a",
      "Stiker",
      "Futbolkaga bosish",
      "Lazer o‘yish",
      "Kitob nashri",
      "Kalendar",
    ],
  },
  {
    id: "financial-services",
    name: "Moliyaviy faoliyat",
    icon: "💳",
    color: "#059669",
    activityTypes: [
      "Sug‘urta",
      "Mikroqarz",
      "Pul o‘tkazmalari",
      "Valyuta ayirboshlash",
      "Lizing",
      "Kredit maslahati",
      "Investitsiya maslahati",
    ],
  },
  {
    id: "import-export",
    name: "Import-eksport",
    icon: "🚢",
    color: "#1D4ED8",
    activityTypes: [
      "Import",
      "Eksport",
      "Bojxona vositachiligi",
      "Xalqaro logistika",
      "Sertifikatlash",
      "Tashqi savdo maslahati",
    ],
  },
];

function normalizeCatalogText(value: string) {
  return value
    .normalize("NFKD")
    .replace(/[‘’ʻʼ`´']/g, "")
    .toLocaleLowerCase("uz")
    .replace(/\s+/g, " ")
    .trim();
}

export function searchCatalogDirections(query: string) {
  const normalizedQuery = normalizeCatalogText(query);

  if (!normalizedQuery) {
    return CATALOG_DIRECTIONS;
  }

  return CATALOG_DIRECTIONS.filter((direction) =>
    normalizeCatalogText(
      `${direction.name} ${direction.activityTypes.join(" ")}`,
    ).includes(normalizedQuery),
  );
}

export function findCatalogDirection(id: string) {
  return CATALOG_DIRECTIONS.find((direction) => direction.id === id);
}
